spring:
  application:
    name: sql-father-backend
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.134.188:3306/sqlfather
    url: jdbc:mysql://localhost:3306/sqlfather
    username: root
#    password: c2412902
    password: 123456
  redis:
    port: 6379
    host: xxx
    password: xxxx
    database: 0

  mail:
    host: smtp.qq.com
    port: 465
    username: xxx
    password: xxx
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
server:
  address: 0.0.0.0
  port: 8102
  servlet:
    context-path: /api
    # session 30 天过期
    session:
      timeout: "P30D"
      cookie:
        same-site: none
        secure: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

#开启swagger配置
swagger:
  open: true
  scanPackage: com.lms.sqlfather
  title: sqltool-server
  version: 1.0.0
  description: sql生成工具

lms:
  global:
    enableRedis: true