// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import { Outlet } from 'umi';
export default function EmptyRoute() {
  return <Outlet />;
}
